export enum ChartType {
  line = 'Line',
  column = 'Column',
  bar = 'Bar',
  area = 'Area',
  pie = 'Pie',
  funnel = 'Funnel',
  gauge = 'Gauge',
  histogram = 'Histogram',
  waterfall = 'Waterfall',
  bullet = 'Bullet',
  liquid = 'Liquid',
  radar = 'Radar',
  scatter = 'Scatter',
  violin = 'Violin',
  facet = 'Facet',
  venn = 'Venn',
  heatmap = 'Heatmap',
  rose = 'Rose',
}
